// src/renderers/lit-element/Controls.ts
import { css, customElement, html, LitElement, property } from "lit-element";
import { tap } from "rxjs/operators";
import { Game } from "../../core";
import { DisposeBag } from "../../helpers";
import { LifeRendererProps } from "../types";

@customElement("gl-le-controls")
export class Controls extends LitElement {
  public static get styles() {
    return css`
      .controls {
        display: flex;
        margin-bottom: 15px;
      }
    `;
  }

  public props!: LifeRendererProps;

  @property()
  private isRunning = false;

  @property()
  private speedLevel = 0;

  private readonly disposeBag = new DisposeBag();

  public connectedCallback() {
    super.connectedCallback();

    this.disposeBag.subscribe(
      this.props.game.isRunning$.pipe(
        tap(newIsRunning => (this.isRunning = newIsRunning)),
      ),
    );

    this.disposeBag.subscribe(
      this.props.game.speedLevel$.pipe(
        tap(newInterval => (this.speedLevel = newInterval)),
      ),
    );
  }

  public disconnectedCallback() {
    this.disposeBag.dispose();
  }

  public render() {
    const { columnsCount, game, rowsCount } = this.props;

    return html`
      <div class="controls">
        ${this.isRunning
          ? html`
              <button @click="${() => game.pause()}">Pause ⏸</button>
            `
          : html`
              <button @click="${() => game.play()}">Play ▶️</button>
            `}

        <button
          @click="${() => {
            game.setLife(Game.getRandomLife({ columnsCount, rowsCount }));
          }}"
        >
          Apply random state
        </button>

        <button @click="${() => game.resetLife()}">Reset</button>

        <input
          type="range"
          @change="${(event: Event) => {
            game.setSpeed(
              Number.parseInt((event.target as HTMLInputElement).value, 10),
            );
          }}"
          value="${this.speedLevel}"
        />
      </div>
    `;
  }
}

// src/renderers/vue/Controls.vue
<template>
  <div class="controls">
    <button @click="pause" v-if="isRunning">Pause ⏸</button>
    <button @click="play" v-else>Play ▶️</button>
    <button @click="applyRandomState">Apply random state</button>
    <button @click="reset">Reset</button>
    <label>
      <input
        type="range"
        v-model="speedLevel"
        value="speedLevel"
        @change="setSpeedLevel"
      />
    </label>
  </div>
</template>

<script lang="ts">
import { tap } from "rxjs/operators";
import Component from "vue-class-component";
import { Game } from "../../core";
import { DisposeBag } from "../../helpers";
import { LifeRenderProps } from "./LifeRenderProps";

@Component
export default class Controls extends LifeRenderProps {
  public isRunning = false;

  public speedLevel = 50;

  private readonly disposeBag = new DisposeBag();

  public mounted() {
    this.disposeBag.subscribe(
      this.game.isRunning$.pipe(
        tap(isRunning => {
          this.isRunning = isRunning;
        }),
      ),
    );

    this.disposeBag.subscribe(
      this.game.speedLevel$.pipe(
        tap(speedLevel => {
          this.speedLevel = speedLevel;
        }),
      ),
    );
  }

  public beforeDestroy() {
    this.disposeBag.dispose();
  }

  public pause() {
    this.game.pause();
  }

  public play() {
    this.game.play();
  }

  public reset() {
    this.game.resetLife();
  }

  public applyRandomState() {
    this.game.setLife(
      Game.getRandomLife({
        columnsCount: this.columnsCount,
        rowsCount: this.rowsCount,
      }),
    );
  }

  public setSpeedLevel(event: Event) {
    this.game.setSpeed(
      Number.parseInt((event.target as HTMLInputElement).value, 10),
    );
  }
}
</script>

<style scoped>
.controls {
  margin-bottom: 15px;
}
</style>
