// src/renderers/react/Controls.tsx
import { css } from "emotion";
import React, { FC, useEffect, useState } from "react";
import { tap } from "rxjs/operators";
import { Game } from "../../core";
import { useLifeRendererProps } from "./LifeRendererPropsContext";

export const Controls: FC<{}> = () => {
  const [isRunning, setIsRunning] = useState(false);
  const [speedLevel, setSpeedLevel] = useState(0);
  const { columnsCount, game, rowsCount } = useLifeRendererProps();

  useEffect(() => {
    const isRunningSubscription = game.isRunning$
      .pipe(tap(newIsRunning => setIsRunning(newIsRunning)))
      .subscribe();

    const speedLevelSubscription = game.speedLevel$
      .pipe(tap(newInterval => setSpeedLevel(newInterval)))
      .subscribe();

    return () => {
      isRunningSubscription.unsubscribe();
      speedLevelSubscription.unsubscribe();
    };
  }, []);

  return (
    <div
      className={css`
        display: flex;
        margin-bottom: 15px;
      `}
    >
      {isRunning ? (
        <button onClick={() => game.pause()}>Pause ⏸</button>
      ) : (
        <button onClick={() => game.play()}>Play ▶️</button>
      )}

      <button
        onClick={() =>
          game.setLife(Game.getRandomLife({ columnsCount, rowsCount }))
        }
      >
        Apply random state
      </button>

      <button onClick={() => game.resetLife()}>Reset</button>

      <input
        type="range"
        onChange={event => {
          game.setSpeed(
            Number.parseInt((event.target as HTMLInputElement).value, 10),
          );
        }}
        value={speedLevel}
      />
    </div>
  );
};

// src/renderers/vue/Controls.vue
<template>
  <div class="controls">
    <button @click="pause" v-if="isRunning">Pause ⏸</button>
    <button @click="play" v-else>Play ▶️</button>
    <button @click="applyRandomState">Apply random state</button>
    <button @click="reset">Reset</button>
    <label>
      <input
        type="range"
        v-model="speedLevel"
        value="speedLevel"
        @change="setSpeedLevel"
      />
    </label>
  </div>
</template>

<script lang="ts">
import { tap } from "rxjs/operators";
import Component from "vue-class-component";
import { Game } from "../../core";
import { DisposeBag } from "../../helpers";
import { LifeRenderProps } from "./LifeRenderProps";

@Component
export default class Controls extends LifeRenderProps {
  public isRunning = false;

  public speedLevel = 50;

  private readonly disposeBag = new DisposeBag();

  public mounted() {
    this.disposeBag.subscribe(
      this.game.isRunning$.pipe(
        tap(isRunning => {
          this.isRunning = isRunning;
        }),
      ),
    );

    this.disposeBag.subscribe(
      this.game.speedLevel$.pipe(
        tap(speedLevel => {
          this.speedLevel = speedLevel;
        }),
      ),
    );
  }

  public beforeDestroy() {
    this.disposeBag.dispose();
  }

  public pause() {
    this.game.pause();
  }

  public play() {
    this.game.play();
  }

  public reset() {
    this.game.resetLife();
  }

  public applyRandomState() {
    this.game.setLife(
      Game.getRandomLife({
        columnsCount: this.columnsCount,
        rowsCount: this.rowsCount,
      }),
    );
  }

  public setSpeedLevel(event: Event) {
    this.game.setSpeed(
      Number.parseInt((event.target as HTMLInputElement).value, 10),
    );
  }
}
</script>

<style scoped>
.controls {
  margin-bottom: 15px;
}
</style>
